### PR TITLE
Motion Magnification

### PR DESCRIPTION
**Pull request by Manezki**
Add motion_magnification.py, allowing post-processing VideoMEG videos to magnify the movement.

Also adds:
* Basic reader for FIF files
* Basic reader for EVL files
* Basic writer for video.dat files
* requirements.txt
* MANIFEST.in for PyVideoMEG
* Matlab code required for Phase Based Motion Processing [Code from MIT, open to be used with non-commercial research](http://people.csail.mit.edu/nwadhwa/phase-video/)

Supports python versions 2.7, 3.3, 3.4 (Limited by matlabengineforpython)

#### Other changes
Changes PyVideoMEG/pyvideomeg/comp_tstamps.py to **use != instead of <> in** comparison. Allowing support for python 3.*

#### Added requirements
* MNE-python - for dealing with .fif-data
* matlabengineforpython - Requires special installation from user. [Explained here](https://github.com/Manezki/VideoMEG/wiki/Intalling-Matlab-engine-for-Python)
* (Pillow) - The whole PIL package is nowadays in Pillow.

#### Documentation
Documentation has been added to the Wiki clone in [here](https://github.com/Manezki/VideoMEG/wiki). And pages "Motion Magnification" & "Installing Matlab engine for Python" should be added after merge.

#### How to test
For a patient case - the script magnifies regions around each annotation saved by Elekta Graph. Here's the basic how-to:
* Add annotation ("REC START") to the very start of MEG-traces ( compress skips on ).
* Save .fif, .evl and .video.dat file to same folder, with same prefix.
* Run motion_magnification.py [path_to_fif_file]
* In Elekta Graph change video-path to look for video.amp.dat
* Open the .fif-file

#### Testing
Testing has been done mainly manually, with Ubuntu 16.04 and python 2.7. But code has been written with 3.* in mind.

For read_data.py some test have been written, but that should only be used as a base for future testing.

#### What has not been tested
Patient files, where skips occur during the acquisition.
Python 3.*

#### Future development
Automatically detect (Without EVL START), the initial skip in the acquisition.

### CODE REVIEW

**Comment by larsoner** [comment]
This sounds like a cool / useful tool. See below for comments.

> Add motion_magnification.py, allowing post-processing VideoMEG videos to magnify the movement.
>
> Also adds:
>
> Basic reader for FIF files
> Basic reader for EVL files
> Basic writer for video.dat files
> requirements.txt
> MANIFEST.in for PyVideoMEG
> Matlab code required for Phase Based Motion Processing Code from MIT, open to be used with non-commercial research

This PR is +8,839 −22, which will make reviewing very difficult. Can you split it into smaller PRs/proposals?

For example:

1. PR to fix bugs (Py3k, etc.), add requirements.txt and MANIFEST.in (for current `master`'s requirements only)
2. PR for adding the FIF reader
3. PR for adding EVL reader (Elekta Graph events list? If so, it's probably better in MNE.)
4. PR for writing video.dat support
5. PR with MATLAB changes.

Each of these has its own potential bugs and API decisions to make. For example, even (2) we probably want to avoid adding a FIF reader at all, and just tell people to use MNE directly (and support objects internally with a soft dependency), which does not sound like how it has been coded. In one big single PR like this it will be much more difficult to keep track of everything and make sure things are done properly.

@andreyzhd do you agree? I'm a secondary contributor here and this is more along the lines of the standards I'm used to from other repos, so it's really up to you.

> Added requirements
>
> MNE-python - for dealing with .fif-data
> matlabengineforpython - Requires special installation from user. Explained here
> (Pillow) - The whole PIL package is nowadays in Pillow.

I haven't looked at the code, but it would be good if requirements like `mne` were optional, i.e., all uses of them were nested in functions rather than at the top of the file.

As far as the matlabengine goes, it would be better to translate the algorithms than call MATLAB if possible. I imagine this is too much work, though?

> Testing
>
> Testing has been done mainly manually, with Ubuntu 16.04 and python 2.7. But code has been written with 3.* in mind.

If you want to translate these tests to proper unit tests that use `py.test` I'm happy to set up automated CI testing to get things going. We probably should have done that from the start :)

> What has not been tested
>
> Patient files, where skips occur during the acquisition.

As in, they're embedded in the FIF file? How is this done during acq? I suspect support for this should also be added to MNE (it's general to FIF not specific to VideoMEG). If you have a FIF file with this data embedded, can you open an MNE issue about it?

**Comment by Manezki** [comment]
Hey,

Most definitely great points - could have structured the PR quite a bit better.
And will do so if it's required. However from the ~9,000 lines, about 8,000 is the Matlab code for the magnification. Converting that to Python would of course be ideal, but currently I don't have the time required.

@larsoner If you could find the time to make a partial code-review - the files that contain most of the changes are:
* PyVideoMEG/bin/motion_magnification.py
* PyVideoMEG/pyvideomeg/read_data.py
* PyVideoMEG/pyvideomeg/video_writer.py

The **MNE-Python** is currently (if I understood correctly) a soft dependency, required by the FifData-class, but without the FIF- the amplification doesn't produce precise results. . ( The FIF-reader is not so much of a reader, but a container for data extracted by MNE. )

**.Evl** is the Elekta's events list, but I didn't come to think about a PR to MNE. This is quite bare-bone solution.

I appreciate the offer for the CI - A lot of the testing has been involving video files or images, and for that reason are not tested automatically. There's only 4-unittests for reading the fif and evl files and involving only the most crucial attributes.

My understanding of the FIF-structure is from MNE's source-code. It appears that FIF records start-time as the time when the sensors first start to send measurement - however it only contains data after the acquisition ( saving the measurement ) ( hope I have my terms in order ) has been started. Resulting in data like this:
[First signals from sensors ][0][0][0][0][0][ Acquisition start ][123][-231][345][123] [Operator stops acquisition ][0][0][0][ Continued ][123][123][-123][123]
This seems to be expected behavior and MNE just skips the 0's from the internal buffer.
So in our case, the problem is that Evl event's are offsets from the start of the measurement, and cannot be used as is for synchronizing the video.

**Comment by larsoner** [comment]
> If you could find the time to make a partial code-review - the files that contain most of the changes are:

Such a partial review requires effectively me to split up your code how a separate PR would, but I am less well equipped to do this task than you are, since they are your changes. So I'd rather wait for the split.

> The MNE-Python is currently (if I understood correctly) a soft dependency, required by the FifData-class, but without the FIF- the amplification doesn't produce precise results. . ( The FIF-reader is not so much of a reader, but a container for data extracted by MNE. )

We'll have to discuss this API implementation in the separate PR(s). In principle there is no reason that any of this functionality needs to be FIF-specific, as it could also be used by any current/old/future other acquisition system that supports trigger-based timing. We should be able to leverage the MNE abstraction away from FIF (e.g., `RawArray`, `RawCTF`, `RawKIT`, etc. as all having `BaseRaw` methods) that makes it system-agnostic.

> .Evl is the Elekta's events list, but I didn't come to think about a PR to MNE. This is quite bare-bone solution.

This definitely sounds like MNE territory, then. If `mne.read_events` doesn't already do what you need to read such files, then we should make it do it. Feel free to open a PR to MNE to do it, and we can iterate on it there instead of here. Or if you don't have time but have some partially working code, put it up in a `gist` and open an MNE issue and I can try to make some PR to add it. But we probably want it in MNE before using it here.

> So in our case, the problem is that Evl event's are offsets from the start of the measurement, and cannot be used as is for synchronizing the video.

I looked into it again and such stop-start loops appear (in `master` at least) in MNE as `BAD_ACQ_SKIP` in Annotations, see:

https://github.com/mne-tools/mne-python/pull/4006

I'm not sure what you need to them for here, but it seems like all information necessary to synchronize should this already be in the object.

> A lot of the testing has been involving video files or images, and for that reason are not tested automatically. There's only 4-unittests for reading the fif and evl files and involving only the most crucial attributes.

The video/image stuff is not really a blocking limitation. We would need someone to take the time to make some very short (10 sec?) video acquisitions to fit our use cases (e.g., motion, things to annotate). Then processing and storage requirements are both reduced to the point that CI (and also fast local) testing is possible.

**Comment by Manezki** [comment]
System-agnostic design I would prefer, however as the PyVideoMeg part seems to be dealing with Elekta's file formats, the necessary changes would be too great to be handled with the time I currently have at my disposal.

To my best knowledge, mne.read_events doesn't seem to help here. Making the implementation for general use, would again require way too much digging into MNE source. Here's the [gist](https://gist.github.com/Manezki/f2dda409342acf6861085737801c6fc5) - if it's useful for MNE it can be used.

BAD_ACQ_SKIP looks like a thing that might resolve the problem with the gaps in the acquisition.

@andreyzhd how do you fell about this?

**Comment by larsoner** [comment]
> System-agnostic design I would prefer, however as the PyVideoMeg part seems to be dealing with Elekta's file formats, the necessary changes would be too great to be handled with the time I currently have at my disposal.

Where does it deal with Elekta formats?

> Making the implementation for general use, would again require way too much digging into MNE source.

Making it general for systems shouldn't require MNE source code searching, just utilizing public MNE APIs. I can see PyVideoMEG needing access to are triggers (`mne.find_events(...)`), and maybe start/stop annotations (`raw.annotations`). So by letting MNE do all the file-format (and thus system-specific) abstraction, we get this essentially for free.

For the graph files, this of course is system specific, which is fine. I'll look into adding it to MNE, and PyVideoMEG should probably load it from there.

My 2c

**Comment by Manezki** [comment]
> Making it general for systems shouldn't require MNE source code searching, just utilizing public MNE APIs.
I found the documentation - and now I see what you mean. Didn't know there's a BaseRaw behind reading. I'll see what I can do.

> Where does it deal with Elekta formats?
The audioData and videoData classes have a check in __init__ for Elektas magic string in the start of the file. I'm not that familiar with the field, so I did not come the question this.

@larsoner another 2cents on this? :)

**Comment by larsoner** [comment]
> The audioData and videoData classes have a check in init for Elektas magic string in the start of the file.

This string does say e.g., `ELEKTA_AUDIO_FILE`, but it gets put in by the [VideoMEG software](https://github.com/andreyzhd/VideoMEG/blob/master/VideoRecStation/src/common.h#L36) during acquisition. In this sense it's a misnomer as it really could have been anything -- maybe better as VIDEOMEG_AUDIO_FILE -- so I don't think this makes it specific to Elekta systems, either.

**Pull request merged**
