### PR TITLE
ENH: Many enhancements

### PR DESCRIPTION
**Pull request by Eric89GXL**
Adds the following features:

1. Option for acquisiton window to be always-on-top (system level).

2. Option to prompt when hitting "stop" ("Are you sure you want to stop the recording?")

3. Recording status: "Found 2 cameras" / "Recording: 00:01:23" / "Saved to 2015-...-*".

4. Disk space status.

5. Option to prompt when starting a recording with low disk space.

6. Option to display audio meters in decibels (logarithmic) instead of linear scale.

7. Added a red "CLIP" warning when audio clips.

8. Scale labels (top and bottom) for audio meters for dB mode.

9. Tightened up the layout of the control window a bit, which should help on our lower-resolution display.

10. **Support for up to 6 cameras.**

~~Also, I recompiled the binary here. @andreyzhd can you check to see if it works for you without recompiling?~~

~~**NOTE:** I have not tested this on our actual production machine yet (only using dummy mode on my development machine so far), so please don't merge until testing has been done on an actual VideoMEG machine (yours or ours).~~

### CODE REVIEW

**Comment by andreyzhd** [comment]
Seems to work OK with your binaries (I've tested with only one camera). Do you actually use 3 cameras? If so, do you have any performance problems?

**Comment by Eric89GXL** [comment]
No, I don't actually use three. I just saw the opportunity to make the code
more DRY and future compatible. It now only takes updating a constant to
increase the maximum camera count.

At some point,  if we want to test speed, we can test everything minus the
firewire overhead (but with added random number generation overhead) using
the dummy mode. We could keep increasing the number of cameras until we see
it break on our systems, which would give us some rule of thumb to work
with.

**Comment by Eric89GXL** [comment]
Also, I am not too worried about people interpreting the dB as SPL, since
the maximum value on the meter is taken as zero.

**Comment by Eric89GXL** [comment]
Pushed an update that states the number of cameras found in the statusbar, and increases the limit to 6. I tested it on my system in dummy mode and it seemed to work. I think this is a reasonable upper limit for now, since I think you could get two cards and run three cameras apiece on them (right?).

I'll test to make sure this actually works on our VideoMEG system locally in a couple of hours. Assuming it works, this should be good to go.

**Comment by Eric89GXL** [comment]
Everything worked great over here, feel free to merge if you're happy.

**Pull request merged**
