### PR TITLE
ENH: Dummy mode and window setting saving

### PR DESCRIPTION
**Pull request by Eric89GXL**
This bundle of source code changes:

1. Enables a "dummy" mode in the config file so that development can be done off-site.

2. Adds persistence of window geometry.

3. Moves toward abstracting the (maximum) number of cameras, and the use of those cameras. Support isn't complete, but at some point if 3 cameras are needed, the changes will be helpful.

4. Sets output files as read-only.

Feel free to nitpick on style, and/or make substantive code content comments. This is my first big PR into the C code, so it would be good to lay the groundwork appropriately for other contributions.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Closes #2

**Comment by Eric89GXL** [comment]
For example: should we use tabs or spaces? I think both were used in the files, and my Qt editor defaulted to spaces, so that's what I went with. If we settle on a standard, after this is merged I can make a commit to convert all the code for uniformity.

**Comment by andreyzhd** [comment]
I also prefer spaces. Let's stick with these.

**Comment by Eric89GXL** [comment]
Cool, I think my editor defaults to spaces. So this is ready for review /
testing / merge from my end.

BTW can you commit your .pro.user file to master? That should might make it
so we have the same build location (release folder), since by default qt
built it elsewhere.

**Comment by andreyzhd** [comment]
On 19.01.2015 02:01, Eric Larson wrote:
> Cool, I think my editor defaults to spaces. So this is ready for review /
> testing / merge from my end.
I'll try to merge it in the in the next few days.
>
> BTW can you commit your .pro.user file to master? That should might 
> make it
> so we have the same build location (release folder), since by default qt
> built it elsewhere. 
I'm not sure whether it's useful. All the paths there are absolute, so 
my .pro.user file won't be good for you and vice versa.

**Comment by Eric89GXL** [comment]
Ahh, alright. Didn't realize they were absolute. Knowing you build with qt5
means I should also be able to update the binary once you're happy with the
code. I'll wait until just before merge, though, to avoid adding multiple
binary updates in this PR.

**Comment by Eric89GXL** [comment]
I take it that you tested this and it worked okay at your end? Do you want to push an updated binary, or should I recompile it here and push?

**Pull request merged**
